on:
    push:
        tags:
            - "v*"

name: Make and build release

jobs:
    build:
        name: Build
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Build
              run: cargo build --release
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: target/release/sssb
                  prerelease: ${{ contains(github.ref, '-') }}
                  latest: ${{ !contains(github.ref, '-') }}
